theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "DiskFree:"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "nvidia_gpu"
label = "GPU"
show_memory = false

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = false
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "net"
device = "eno1"
ssid = true
speed_up = false
speed_down = false


[[block]]
device ="BAT0"
block = "battery"
interval = 10
upower =  true
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
timezone = "GMT"
format = "%a %d/%m %R"
